server:
  port: 5000
spring:
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: 301123gsw
  application:
    name: expert-service
  datasource:
    url: jdbc:mysql://localhost:3306/parent_service
    username: root
    password: 123456123456
    driver-class-name: com.mysql.jdbc.Driver
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  mail:
    host: smtp.163.com
    username: 13843842030@163.com
    password: FWeewtAFefkxskU7
    default-encoding: UTF-8
    port: 465
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.expert.service.mapper
  configuration:
    map-underscore-to-camel-case: true