server:
  port: 8000
spring:
  application:
    name: parent-service
  datasource:
    url: jdbc:mysql://192.168.150.101:3306/parent_service
    username: root
    password: 301123gsw
    driver-class-name: com.mysql.jdbc.Driver
  data:
    redis:
      database: 0
      host: 192.168.150.101
      port: 6379

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.parent.service.mapper
  configuration:
    map-underscore-to-camel-case: true